### ISSUE TITLE
make install-ubuntu failed, had to finish nvm install packages manually

### ISSUE THREAD

**Issue by yubrshen** [matthiasn/meins#23]
executing 
make install-ubuntu
ran into a few problems. 

Java 10 being outdated. (I just comment out the part on Java 10 installation, as I already have it.)

The command 'source $HOME/.bashrc' became:
source OME/.bashrc
of course, failed. 
I just manually execute the rest. 

I attach the trace of the execution here.
[make-install-ubuntu.log](https://github.com/matthiasn/meins/files/2923308/make-install-ubuntu.log)

**Comment by yubrshen** [comment]
Failure with installing Java related is due to the fact that the repository changed to provide Java 11, so all the mention of Java 10 should become Java 11 to work.

**Comment by matthiasn** [comment]
Hi Yu, I hadn't touched that section of the `Makefile` in a while. I removed installing the JDK and NVM from here, and adapted the README accordingly. Also renamed the targets. Not sure what's happening with the `source OME/.bashrc` but since I removed that line as well, I'm closing this. Thanks for reporting.
